### ISSUE TITLE
Thanks haekb! Great tool! Does it support Lithtech Jupiter (DAT v85)? 

### ISSUE THREAD

**Issue by naruto70882** [haekb/godot-dat-reader#1]
I want to use it to convert the map of NOLF2 to UE4 for reset. Unfortunately, I don't understand the godot scripting language.

**Comment by goshante** [comment]
Bumping the question

**Comment by haekb** [comment]
Hello! 

It currently only supports the formats listed in the readme. Here's a snapshot. 
![image](https://user-images.githubusercontent.com/3683240/122621685-1cd86380-d04b-11eb-8ab7-ac97eca14b87.png)


Eventually there will be a UI re-work which will allow quite a bit of functionality, but I'm quite busy lately.
